import { Property } from '@/lib/types'

export const mockProperties: Property[] = [
  {
    id: 'mock-karen-residence',
    title: 'Garden Residence in Karen',
    description:
      'A landscaped family residence with generous entertaining zones, a quiet office wing, and refined indoor-outdoor living.',
    propertyType: 'villa',
    address: 'Miotoni Road',
    city: 'Nairobi',
    county: 'Karen',
    latitude: undefined,
    longitude: undefined,
    price: 68000000,
    currency: 'KES',
    totalRooms: 9,
    bedrooms: 5,
    bathrooms: 5,
    livingRooms: 2,
    kitchens: 1,
    plotSize: '0.6 acres',
    builtArea: '7,200 sq ft',
    constructionYear: 2021,
    verificationStatus: 'verified',
    verifiedBy: 'KK Real Estate',
    verifiedAt: '2026-04-29T00:00:00.000Z',
    verificationNotes: 'Preview data for local development.',
    addedBy: 'system',
    isAvailable: true,
    viewsCount: 0,
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1400&q=80'],
    createdAt: '2026-04-29T00:00:00.000Z',
    updatedAt: '2026-04-29T00:00:00.000Z',
  },
  {
    id: 'mock-westlands-apartment',
    title: 'Skyline Apartment in Westlands',
    description:
      'A polished city address with concierge access, warm material finishes, and strong rental positioning for investors.',
    propertyType: 'apartment',
    address: 'Brookside Drive',
    city: 'Nairobi',
    county: 'Westlands',
    latitude: undefined,
    longitude: undefined,
    price: 31000000,
    currency: 'KES',
    totalRooms: 6,
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 1,
    kitchens: 1,
    plotSize: 'N/A',
    builtArea: '2,300 sq ft',
    constructionYear: 2023,
    verificationStatus: 'verified',
    verifiedBy: 'KK Real Estate',
    verifiedAt: '2026-04-29T00:00:00.000Z',
    verificationNotes: 'Preview data for local development.',
    addedBy: 'system',
    isAvailable: true,
    viewsCount: 0,
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80'],
    createdAt: '2026-04-29T00:00:00.000Z',
    updatedAt: '2026-04-29T00:00:00.000Z',
  },
  {
    id: 'mock-nyali-villa',
    title: 'Signature Villa in Nyali',
    description:
      'A coastal home curated for private family use, featuring layered terraces, large suites, and investment-ready presentation.',
    propertyType: 'mansion',
    address: 'Links Road',
    city: 'Mombasa',
    county: 'Nyali',
    latitude: undefined,
    longitude: undefined,
    price: 85000000,
    currency: 'KES',
    totalRooms: 11,
    bedrooms: 6,
    bathrooms: 6,
    livingRooms: 2,
    kitchens: 2,
    plotSize: '0.8 acres',
    builtArea: '8,900 sq ft',
    constructionYear: 2020,
    verificationStatus: 'verified',
    verifiedBy: 'KK Real Estate',
    verifiedAt: '2026-04-29T00:00:00.000Z',
    verificationNotes: 'Preview data for local development.',
    addedBy: 'system',
    isAvailable: true,
    viewsCount: 0,
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=80'],
    createdAt: '2026-04-29T00:00:00.000Z',
    updatedAt: '2026-04-29T00:00:00.000Z',
  },
]
